@startuml
skinparam defaultFontName VL Gothic
actor クライアントA
actor クライアントB
participant ハンドラー
クライアントA -> ハンドラー: 接続/ユーザー名
ハンドラー --> クライアントA: 入室通知
クライアントA -> ハンドラー: メッセージ
ハンドラー --> クライアントA: ブロードキャスト
ハンドラー --> クライアントB: ブロードキャスト
クライアントB -> ハンドラー: 切断
ハンドラー --> クライアントA: 退室通知
@enduml
