spring.datasource.url=jdbc:h2:file:./data/jparestapi;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
# REST APIではビュー描画がないため、遅延ロードの温床になるOpen Session in Viewは無効化する
spring.jpa.open-in-view=false
